import { AnalysisReport } from './types';

/** Format a byte count into a human-readable string (e.g. "4.2 MB"). */
export function formatBytes(bytes: number): string {
  if (!bytes || bytes < 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const value = bytes / Math.pow(1024, i);
  return `${value.toFixed(i === 0 ? 0 : 1)} ${units[i]}`;
}

/** Read a File as a base64 data URL (e.g. "data:image/png;base64,...."). */
export function readFileAsDataURL(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(reader.error ?? new Error('Failed to read file'));
    reader.readAsDataURL(file);
  });
}

/** Map an arbitrary upload/content type to one of the report categories. */
export function resolveReportType(type: string): AnalysisReport['type'] {
  if (type === 'image' || type === 'photo') return 'photo';
  if (type === 'video' || type === 'speech') return 'video';
  if (type === 'assignment') return 'assignment';
  return 'news';
}

/** Trigger a browser download for the given text content. */
export function downloadTextFile(filename: string, content: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Generate and download a styled PDF forensic report (Pro feature).
 *  jsPDF is loaded on demand so it stays out of the initial bundle. */
export async function downloadReportPdf(report: AnalysisReport): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = margin;

  const line = (gap = 16) => { y += gap; };
  const wrap = (text: string, size: number, style: 'normal' | 'bold' = 'normal', gap = 14) => {
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
    for (const ln of doc.splitTextToSize(text, contentW)) {
      if (y > doc.internal.pageSize.getHeight() - margin) { doc.addPage(); y = margin; }
      doc.text(ln, margin, y);
      y += gap;
    }
  };

  // Header band
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('TruthAI Forensic Report', margin, 44);
  y = 100;

  doc.setTextColor(15, 23, 42);
  wrap(report.title, 15, 'bold', 20);

  doc.setTextColor(100, 116, 139);
  wrap(`Analyzed: ${report.timestamp}    Type: ${report.type}`, 10, 'normal', 18);

  // Verdict
  doc.setTextColor(15, 23, 42);
  wrap(`Verdict: ${report.status.toUpperCase()}   ·   Truth Score: ${report.truthScore}%   ·   Risk: ${report.riskLevel.toUpperCase()}`, 12, 'bold', 22);

  doc.setTextColor(51, 65, 85);
  wrap(report.explanation, 11, 'normal', 16);
  line(8);

  // Metrics
  doc.setTextColor(37, 99, 235);
  wrap('Forensic Signals', 13, 'bold', 20);
  doc.setTextColor(51, 65, 85);
  for (const m of report.metrics) {
    wrap(`• ${m.name} — ${m.label} (${m.score}/100)`, 11, 'bold', 15);
    wrap(m.description, 10, 'normal', 14);
    line(4);
  }

  // Specs
  if (report.resolution || report.method) {
    line(6);
    doc.setTextColor(37, 99, 235);
    wrap('Scan Specifications', 13, 'bold', 18);
    doc.setTextColor(51, 65, 85);
    wrap(
      `Resolution: ${report.resolution || 'N/A'}    Color: ${report.colorSpace || 'N/A'}    Depth: ${report.bitDepth || 'N/A'}    Engine: ${report.method || 'N/A'}`,
      10, 'normal', 14
    );
  }

  // Footer
  const h = doc.internal.pageSize.getHeight();
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(9);
  doc.text('Generated by TruthAI Pro · truthai', margin, h - 30);

  const safe = report.title.replace(/[^a-z0-9]+/gi, '_').slice(0, 40) || 'report';
  doc.save(`truthai_${safe}.pdf`);
}

/** Build a CSV ledger from a list of reports. */
export function reportsToCSV(reports: AnalysisReport[]): string {
  const header = ['Title', 'Type', 'Analyzed At', 'Scope', 'Verdict', 'Risk', 'Truth Score (%)'];
  const escape = (v: string) => `"${String(v).replace(/"/g, '""')}"`;
  const rows = reports.map((r) =>
    [r.title, r.type, r.timestamp, r.fileSize ?? 'N/A', r.status, r.riskLevel, String(r.truthScore)]
      .map(escape)
      .join(',')
  );
  return [header.map(escape).join(','), ...rows].join('\n');
}
